# Dynamic configuration
# in configuration/certificates.yaml

# tls:
#   certificates:
#     # first certificate
#     - certFile: localhost-cert/cert.pem
#       keyFile: localhost-cert/key.pem

#     # # second certificate
#     # - certFile: /path/to/other.cert
#     #   keyFile: /path/to/other.key

tls:
  certificates:
    - certFile: "/localhost-cert/cert.pem"
      keyFile: "/localhost-cert/key.pem"
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: "/localhost-cert/cert.pem"
        keyFile: "/localhost-cert/key.pem"